spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 3250325q
    hikari:
      schema: user_schema
      connection-init-sql: create schema if not exists user_schema
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariCP

app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m
  bankAccount:
    balanceUpdateRate: 60000